### ISSUE TITLE
Unable to run application after docker build 

### ISSUE THREAD

**Issue by godwinpinto** [coauth/coauth-core#1]
**Describe the bug**
When running the application as a container, a null pointer error is noticed

**Docker build commands**
./mvnw clean package
docker build -f src/main/docker/Dockerfile.jvm -t godwinpinto/coauth-module-totp:1.0.0-SNAPSHOT .

**Error Log:**
INFO exec -a "java" java -XX:MaxRAMPercentage=80.0 -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+ExitOnOutOfMemoryError -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -cp "." -jar /deployments/quarkus-run.jar
INFO running in /deployments
Nov 23, 2023 10:35:48 AM org.hibernate.Version
INFO: HHH000412: Hibernate ORM core version %s
Nov 23, 2023 10:35:48 AM org.hibernate.cfg.Environment
INFO: HHH000406: Using bytecode reflection optimizer
Nov 23, 2023 10:35:48 AM org.hibernate.orm.deprecation
WARN: HHH90000025: %s does not need to be specified explicitly using 'hibernate.dialect' (remove the property setting and it will be selected by default)
Nov 23, 2023 10:35:49 AM org.hibernate.validator.internal.util.Version
INFO: HV000001: Hibernate Validator %s
Nov 23, 2023 10:35:50 AM org.hibernate.resource.beans.container.spi.AbstractCdiBeanContainer stop
INFO: HHH10005004: Stopping BeanContainer : %s
Nov 23, 2023 10:35:50 AM io.quarkus.runtime.ApplicationLifecycleManager run
ERROR: Failed to start application (with profile [prod])
java.lang.RuntimeException: Failed to start quarkus
at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
at io.quarkus.runtime.Application.start(Application.java:101)
at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
at io.quarkus.runner.GeneratedMain.main(Unknown Source)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
Caused by: java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "org.eclipse.microprofile.config.ConfigValue.getValue()" is null
at io.quarkus.runtime.configuration.ConfigRecorder.handleConfigChange(ConfigRecorder.java:44)
at io.quarkus.deployment.steps.ConfigGenerationBuildStep$checkForBuildTimeConfigChange1532146938.deploy_9(Unknown Source)
at io.quarkus.deployment.steps.ConfigGenerationBuildStep$checkForBuildTimeConfigChange1532146938.deploy(Unknown Source)
... 13 more

**Comment by godwinpinto** [comment]
Variables if defined as ${VARIABLE:SERVICE:PORT} causes the issue

**Comment by godwinpinto** [comment]
Changes committed to branch
